language: node_js
stages:
  - test
  - name: deploy integration
    if: branch = master
  - name: deploy uat
    if: tag is present
  - name: deploy live
    if: tag =~ ^((?!beta).)*$
jobs:
  include:
    - stage: test

    - stage: deploy
      env: BUCKET=integration.kinesisexplorer.com
      script: npm run build
      if: branch = master
      deploy: &deploy
        provider: s3
        region: ap-southeast-2
        skip_cleanup: true
        bucket: $BUCKET
    - env: BUCKET=uat.kinesisexplorer.com
      if: tag is present
      script: npm run build
      deploy:
        <<: *deploy
    - env: BUCKET=www.kinesisexplorer.com
      deploy:
        <<: *deploy