language: node_js
jobs:
  include:
    - stage: test

    - stage: deploy
      env: BUCKET=integration.kinesisexplorer.com
      if: branch = master
      script: npm run build
      deploy: &deploy
        provider: s3
        region: ap-southeast-2
        skip_cleanup: true
        bucket: $BUCKET
    - env: BUCKET=uat.kinesisexplorer.com
      if: tag is present
      script: npm run build
      deploy:
        <<: *deploy
    - env: BUCKET=www.kinesisexplorer.com
      if: tag is present && tag =~ ^((?!beta).)*$
      script: npm run build
      deploy:
        <<: *deploy